use serde::{Deserialize, Serialize};

/// Metadata associated with file
#[derive(Clone, Debug, Default, Deserialize, Serialize)]
#[serde(tag = "type")]
pub enum Metadata {
    /// File is just a generic uncategorised file
    #[default]
    File,
    /// File contains textual data and should be displayed as such
    Text,
    /// File is an image with specific dimensions
    Image { width: isize, height: isize },
    /// File is a video with specific dimensions
    Video { width: isize, height: isize },
    /// File is audio
    Audio,
}

/// Representation of a File on Revolt
/// Generated by Autumn
#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct File {
    /// Unique Id
    #[serde(rename = "_id")]
    pub id: String,
    /// Tag / bucket this file was uploaded to
    pub tag: String,
    /// Original filename
    pub filename: String,
    /// Parsed metadata of this file
    pub metadata: Metadata,
    /// Raw content type of this file
    pub content_type: String,
    /// Size of this file (in bytes)
    pub size: isize,
}

impl File {
    pub fn autumn_url(&self, autumn_base_url: &str) -> String {
        format!("{autumn_base_url}/{}/{}", &self.tag, &self.id)
    }
}
